# Generated by Django 2.0.4 on 2018-04-16 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=20)),
                ('describe', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('process_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Food_Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='food_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis.Food_Class'),
        ),
    ]
